
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.6]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install venv and dependencies
      run: ./setup.sh
    - name: pylint
      run: ./run-pylint.sh
    - name: Tests
      run: ./run-tests.sh
    - name: Integration Tests
      env:
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        AD_INT_TEST_RECIPIENT: ${{ secrets.AD_INT_TEST_RECIPIENT }}
      run: ./run-integration-tests.sh
